[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-Powerplug"
version = "1.0.0"
description = "A simple plugin for sending http requests to turn on a tasmota smart switch"
authors = [
    {name = "Injourn", email = "thatguywhowas@live.com"}
]
readme = {file = "README.md", content-type = "text/markdown"}
dynamic = [
    "license"
]

requires-python = ">=3.7, <4"

# any additional requirements (besides OctoPrint) should be listed here
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_powerplug",
    "octoprint_powerplug.*"
]

[project.entry-points."octoprint.plugin"]
powerplug = "octoprint_powerplug"

[project.urls]
Homepage = "https://github.com/Injourn/OctoPrint-Powerplug"

[project.optional-dependencies]
develop = [
    "go-task-bin"
]
